"""
Database Models for Flask-Admin
Re-exports the models from src/models with Flask-Admin customizations
"""
import sys
import os

# Add src to path for imports
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import uuid

db = SQLAlchemy()

class ActiveIngredient(db.Model):
    """Raw ingredient data from original dataset"""
    __tablename__ = 'active_ingredients'
    
    ingredient_id = db.Column(db.String, primary_key=True)  # UUID generated by database
    name = db.Column(db.String(255), nullable=False)
    
    # Relationships
    mappings = db.relationship('IngredientMapping', backref='raw_ingredient', lazy=True)
    
    def __str__(self):
        return f"{self.name}"
    
    def __repr__(self):
        return f'<ActiveIngredient {self.name}>'

class ActiveIngredientExtended(db.Model):
    """Clean, standardized ingredient data"""
    __tablename__ = 'active_ingredients_extended'
    
    id = db.Column(db.Integer, primary_key=True)
    ingredient_name = db.Column(db.String(255), nullable=False, unique=True)
    short_description = db.Column(db.Text)
    common_uses = db.Column(db.Text)
    side_effects = db.Column(db.Text)
    contraindications = db.Column(db.Text)
    last_updated = db.Column(db.DateTime, default=datetime.utcnow)
    processing_status = db.Column(db.String(50), default='pending')
    error_message = db.Column(db.Text)
    
    # Relationships
    mappings = db.relationship('IngredientMapping', backref='extended_ingredient', lazy=True)
    
    def __str__(self):
        return self.ingredient_name
    
    def __repr__(self):
        return f'<ActiveIngredientExtended {self.ingredient_name}>'

class IngredientMapping(db.Model):
    """Many-to-many mapping between raw and extended ingredients"""
    __tablename__ = 'ingredient_mappings'
    
    id = db.Column(db.Integer, primary_key=True)
    raw_ingredient_id = db.Column(db.String, db.ForeignKey('active_ingredients.ingredient_id'), nullable=False)
    extended_ingredient_id = db.Column(db.Integer, db.ForeignKey('active_ingredients_extended.id'), nullable=False)
    mapping_type = db.Column(db.String(50), nullable=False)
    confidence = db.Column(db.Numeric(3,2), nullable=False)
    extraction_method = db.Column(db.String(50))
    original_text = db.Column(db.Text)
    ai_notes = db.Column(db.Text)
    similarity_score = db.Column(db.Numeric(3,2))
    verified = db.Column(db.Boolean, default=False)
    verified_by = db.Column(db.String(100))
    verified_at = db.Column(db.DateTime)
    verification_notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = db.Column(db.String(100), default='system')
    
    def __str__(self):
        return f"{self.raw_ingredient.name} → {self.extended_ingredient.ingredient_name}"
    
    def __repr__(self):
        return f'<IngredientMapping {self.id}: {self.mapping_type}>'

class IngredientMappingLog(db.Model):
    """Audit log for ingredient mapping changes"""
    __tablename__ = 'ingredient_mapping_log'
    
    id = db.Column(db.Integer, primary_key=True)
    mapping_id = db.Column(db.Integer, db.ForeignKey('ingredient_mappings.id'))
    action = db.Column(db.String(20), nullable=False)  # INSERT, UPDATE, DELETE
    old_values = db.Column(db.JSON)
    new_values = db.Column(db.JSON)
    changed_by = db.Column(db.String(100), default='system')
    changed_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def __str__(self):
        return f"{self.action} on mapping {self.mapping_id} at {self.changed_at}"
    
    def __repr__(self):
        return f'<IngredientMappingLog {self.id}: {self.action}>'